const stocks = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    industry: "Consumer Electronics",
    marketCap: 2700000000000,
    peRatio: 28.3,
    logoUrl: "https://logo.clearbit.com/apple.com",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    sector: "Technology",
    industry: "Software—Infrastructure",
    marketCap: 2400000000000,
    peRatio: 35.1,
    logoUrl: "https://logo.clearbit.com/microsoft.com",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    marketCap: 1800000000000,
    peRatio: 24.8,
    logoUrl: "https://logo.clearbit.com/abc.xyz",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
    marketCap: 1700000000000,
    peRatio: 58.2,
    logoUrl: "https://logo.clearbit.com/amazon.com",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    sector: "Consumer Discretionary",
    industry: "Automobiles",
    marketCap: 900000000000,
    peRatio: 75.6,
    logoUrl: "https://logo.clearbit.com/tesla.com",
  },
  {
    symbol: "FB",
    name: "Meta Platforms Inc.",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    marketCap: 800000000000,
    peRatio: 23.4,
    logoUrl: "https://logo.clearbit.com/meta.com",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 1000000000000,
    peRatio: 50.3,
    logoUrl: "https://logo.clearbit.com/nvidia.com",
  },
  {
    symbol: "BRK.B",
    name: "Berkshire Hathaway Inc.",
    sector: "Financials",
    industry: "Insurance—Diversified",
    marketCap: 700000000000,
    peRatio: 8.5,
    logoUrl: "https://logo.clearbit.com/berkshirehathaway.com",
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    sector: "Financials",
    industry: "Credit Services",
    marketCap: 500000000000,
    peRatio: 30.2,
    logoUrl: "https://logo.clearbit.com/visa.com",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    industry: "Drug Manufacturers—General",
    marketCap: 450000000000,
    peRatio: 17.8,
    logoUrl: "https://logo.clearbit.com/jnj.com",
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    sector: "Consumer Staples",
    industry: "Discount Stores",
    marketCap: 400000000000,
    peRatio: 21.5,
    logoUrl: "https://logo.clearbit.com/walmart.com",
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    sector: "Consumer Staples",
    industry: "Household & Personal Products",
    marketCap: 350000000000,
    peRatio: 25.4,
    logoUrl: "https://logo.clearbit.com/pg.com",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    sector: "Financials",
    industry: "Banks—Diversified",
    marketCap: 450000000000,
    peRatio: 10.8,
    logoUrl: "https://logo.clearbit.com/jpmorganchase.com",
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Incorporated",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    marketCap: 500000000000,
    peRatio: 22.1,
    logoUrl: "https://logo.clearbit.com/unitedhealthgroup.com",
  },
  {
    symbol: "HD",
    name: "The Home Depot Inc.",
    sector: "Consumer Discretionary",
    industry: "Home Improvement Retail",
    marketCap: 350000000000,
    peRatio: 20.3,
    logoUrl: "https://logo.clearbit.com/homedepot.com",
  },
  {
    symbol: "MA",
    name: "Mastercard Incorporated",
    sector: "Financials",
    industry: "Credit Services",
    marketCap: 400000000000,
    peRatio: 35.6,
    logoUrl: "https://logo.clearbit.com/mastercard.com",
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    sector: "Communication Services",
    industry: "Entertainment",
    marketCap: 200000000000,
    peRatio: 18.9,
    logoUrl: "https://logo.clearbit.com/disney.com",
  },
  {
    symbol: "PYPL",
    name: "PayPal Holdings Inc.",
    sector: "Financials",
    industry: "Credit Services",
    marketCap: 150000000000,
    peRatio: 25.7,
    logoUrl: "https://logo.clearbit.com/paypal.com",
  },
  {
    symbol: "NFLX",
    name: "Netflix Inc.",
    sector: "Communication Services",
    industry: "Entertainment",
    marketCap: 200000000000,
    peRatio: 30.4,
    logoUrl: "https://logo.clearbit.com/netflix.com",
  },
  {
    symbol: "ADBE",
    name: "Adobe Inc.",
    sector: "Technology",
    industry: "Software—Infrastructure",
    marketCap: 250000000000,
    peRatio: 40.2,
    logoUrl: "https://logo.clearbit.com/adobe.com",
  },
  {
    symbol: "CRM",
    name: "Salesforce Inc.",
    sector: "Technology",
    industry: "Software—Application",
    marketCap: 200000000000,
    peRatio: 50.1,
    logoUrl: "https://logo.clearbit.com/salesforce.com",
  },
  {
    symbol: "INTC",
    name: "Intel Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 150000000000,
    peRatio: 12.3,
    logoUrl: "https://logo.clearbit.com/intel.com",
  },
  {
    symbol: "ORCL",
    name: "Oracle Corporation",
    sector: "Technology",
    industry: "Software—Infrastructure",
    marketCap: 250000000000,
    peRatio: 30.5,
    logoUrl: "https://logo.clearbit.com/oracle.com",
  },
  {
    symbol: "PEP",
    name: "PepsiCo Inc.",
    sector: "Consumer Staples",
    industry: "Beverages—Non-Alcoholic",
    marketCap: 250000000000,
    peRatio: 25.8,
    logoUrl: "https://logo.clearbit.com/pepsico.com",
  },
  {
    symbol: "KO",
    name: "The Coca-Cola Company",
    sector: "Consumer Staples",
    industry: "Beverages—Non-Alcoholic",
    marketCap: 240000000000,
    peRatio: 24.1,
    logoUrl: "https://logo.clearbit.com/coca-cola.com",
  },
  {
    symbol: "NKE",
    name: "Nike Inc.",
    sector: "Consumer Discretionary",
    industry: "Footwear & Accessories",
    marketCap: 200000000000,
    peRatio: 35.2,
    logoUrl: "https://logo.clearbit.com/nike.com",
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    marketCap: 400000000000,
    peRatio: 9.8,
    logoUrl: "https://logo.clearbit.com/exxonmobil.com",
  },
  {
    symbol: "CVX",
    name: "Chevron Corporation",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    marketCap: 300000000000,
    peRatio: 10.5,
    logoUrl: "https://logo.clearbit.com/chevron.com",
  },
  {
    symbol: "PFE",
    name: "Pfizer Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers—General",
    marketCap: 200000000000,
    peRatio: 12.7,
    logoUrl: "https://logo.clearbit.com/pfizer.com",
  },
  {
    symbol: "MRK",
    name: "Merck & Co. Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers—General",
    marketCap: 250000000000,
    peRatio: 14.9,
    logoUrl: "https://logo.clearbit.com/merck.com",
  },
  {
    symbol: "T",
    name: "AT&T Inc.",
    sector: "Communication Services",
    industry: "Telecom Services",
    marketCap: 150000000000,
    peRatio: 7.5,
    logoUrl: "https://logo.clearbit.com/att.com",
  },
  {
    symbol: "VZ",
    name: "Verizon Communications Inc.",
    sector: "Communication Services",
    industry: "Telecom Services",
    marketCap: 200000000000,
    peRatio: 8.3,
    logoUrl: "https://logo.clearbit.com/verizon.com",
  },
  {
    symbol: "CSCO",
    name: "Cisco Systems Inc.",
    sector: "Technology",
    industry: "Communication Equipment",
    marketCap: 250000000000,
    peRatio: 18.6,
    logoUrl: "https://logo.clearbit.com/cisco.com",
  },
  {
    symbol: "BA",
    name: "The Boeing Company",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    marketCap: 150000000000,
    peRatio: 20.4,
    logoUrl: "https://logo.clearbit.com/boeing.com",
  },
  {
    symbol: "MMM",
    name: "3M Company",
    sector: "Industrials",
    industry: "Conglomerates",
    marketCap: 100000000000,
    peRatio: 15.2,
    logoUrl: "https://logo.clearbit.com/3m.com",
  },
  {
    symbol: "GE",
    name: "General Electric Company",
    sector: "Industrials",
    industry: "Conglomerates",
    marketCap: 120000000000,
    peRatio: 18.1,
    logoUrl: "https://logo.clearbit.com/ge.com",
  },
  {
    symbol: "CAT",
    name: "Caterpillar Inc.",
    sector: "Industrials",
    industry: "Farm & Heavy Construction Machinery",
    marketCap: 150000000000,
    peRatio: 16.7,
    logoUrl: "https://logo.clearbit.com/caterpillar.com",
  },
  {
    symbol: "UPS",
    name: "United Parcel Service Inc.",
    sector: "Industrials",
    industry: "Integrated Freight & Logistics",
    marketCap: 180000000000,
    peRatio: 20.1,
    logoUrl: "https://logo.clearbit.com/ups.com",
  },
  {
    symbol: "FDX",
    name: "FedEx Corporation",
    sector: "Industrials",
    industry: "Integrated Freight & Logistics",
    marketCap: 120000000000,
    peRatio: 15.4,
    logoUrl: "https://logo.clearbit.com/fedex.com",
  },
  {
    symbol: "GS",
    name: "The Goldman Sachs Group Inc.",
    sector: "Financials",
    industry: "Capital Markets",
    marketCap: 120000000000,
    peRatio: 9.6,
    logoUrl: "https://logo.clearbit.com/goldmansachs.com",
  },
  {
    symbol: "MS",
    name: "Morgan Stanley",
    sector: "Financials",
    industry: "Capital Markets",
    marketCap: 150000000000,
    peRatio: 11.2,
    logoUrl: "https://logo.clearbit.com/morganstanley.com",
  },
  {
    symbol: "BK",
    name: "The Bank of New York Mellon Corporation",
    sector: "Financials",
    industry: "Asset Management",
    marketCap: 50000000000,
    peRatio: 10.5,
    logoUrl: "https://logo.clearbit.com/bnymellon.com",
  },
  {
    symbol: "SCHW",
    name: "The Charles Schwab Corporation",
    sector: "Financials",
    industry: "Capital Markets",
    marketCap: 120000000000,
    peRatio: 18.3,
    logoUrl: "https://logo.clearbit.com/schwab.com",
  },
];

export default stocks;
